baseurl = "https://valentin.liegrois.com/"
title = "Valentin Liegrois"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Nostromo"

[params]
    author = "Valentin Liegrois"
    info = "Consultant Cloud"
    description = "Site web de Valentin Liegrois"
    keywords = "consultant,portfolio,personal"
    avatarurl = "img/avatar.jpg"
    
    inverted = true

    favicon_32 = "/public/img/favicon-32x32.png"
    favicon_16 = "/public/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = false
    colorscheme = "dark"

    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/nostromooo/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/valentin-liegrois/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/nox_fr/"
[[params.social]]
    name = "Spotify"
    icon = "fab fa-spotify fa-2x"
    weight = 3
    url = "https://open.spotify.com/user/1190274945?si=J2HVfX80R1iZNGahpCnOcg"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "http://blog.alterway.fr/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"
